version: '3'

services:
    db:
        image: postgres
        volumes:
            - ./docker/postgres/:/docker-entrypoint-initdb.d/
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: "fs"
            POSTGRES_USER: "fs"
            POSTGRES_DB: "fs"
            PGDATA: "/var/lib/postgresql/data/db/"

    web:
        image: fs:latest
        restart: always
        volumes:
            - ~/.ipython:/root/.ipython
            - .:/app
        ports:
            - "8007:8000"
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - db
            - redis

    # queue:
    #     image: rabbitmq:3.6.6-management
    #     environment:
    #         - RABBITMQ_DEFAULT_USER=admin
    #         - RABBITMQ_DEFAULT_PASS=admin
    #         - RABBITMQ_DEFAULT_VHOST=fs
    #         - TZ=Europe/Kiev
    #     ports:
    #         - "5673:5672"
    #         - "15673:15672"

    worker:
        image: fs:latest
        environment:
            DJANGO_SETTINGS_MODULE: fs.settings
        command: celery worker -A fs -E -l info
        volumes:
          - .:/app
        depends_on:
          - db
          - redis

    celery:
        image: fs:latest
        command: celery -A fs beat -l info
        environment:
            DJANGO_SETTINGS_MODULE: fs.settings
            TZ: Europe/Kiev
        volumes:
            - .:/app
        depends_on:
            - db

    flower:
        image: fs:latest
        command: celery -A fs flower -E -l info
        environment:
            DJANGO_SETTINGS_MODULE: fs.settings
        ports:
            - "5553:5555"
        volumes:
            - .:/app

    redis:
        image: redis:latest
        ports:
          - "6373:6379"
        volumes:
          - redis_db:/data

    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3

    # kibana:
    #     image: docker.elastic.co/kibana/kibana:5.4.3
    #     environment:
    #         - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    #     depends_on:
    #         - elasticsearch

volumes:
    db_data:
    redis_db:
